project_id = "fvveqziyusjgqejowkfp"

[functions.ev-cms-mobile-wallet-create-razorpay-order]
verify_jwt = false

[functions.ev-cms-mobile-wallet-verify-razorpay-payment]
verify_jwt = false

[functions.ev-cms-mobile-session-create-razorpay-order]
verify_jwt = false

[functions.ev-cms-mobile-session-verify-razorpay-payment]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
